### PR TITLE
Netbox: Make username and password config optional

### PR DESCRIPTION
**Pull request by taylortbb**
I'm unable to ever re-start this add-on currently. I believe this is the fix, but I'm also surprised to be the first person to hit such a major issue. Please let me know if there's something I'm missing here.

### CODE REVIEW

**Comment by casperklein** [comment]
Please describe, what you did, what happened and what you expected to happen.

> I'm unable to ever re-start this add-on currently

I can only guess, that you created an admin user? Afterwards, just clear the two text boxes (username & password) and hit the "safe" button. Then restart the addon.

**Comment by taylortbb** [comment]
That's correct, I installed the add-on, set a username and password to create an admin user, and then started the add-on. So far so good. I then attempted to clear the text boxes, however Home Asisstant informed me that the username and password fields were mandatory, and would not accept a blank entry. Unable to set the username/password to blank, I became unable to re-start the add-on (as it would attempt to re-create the user).

If you look at https://developers.home-assistant.io/docs/add-ons/configuration/#options--schema it says "To make an option optional, put ? at the end of the data type, otherwise it will be a required value." As this add-on does not have a ? at the end of the type it appears Home Assistants behaviour matches the documentation.

**Comment by taylortbb** [comment]
Perhaps the screenshot will make the issue clearer.

Netbox Mandatory Username Password

**Comment by casperklein** [comment]
Username / Password are not optional (as you said), so try this:

```
user: ""
password: ""
https: false
certfile: fullchain.pem
keyfile: privatekey.pem
```

I see you edit in yaml mode. Can you try in "UI" mode and see of that works?

> "To make an option optional, put ? at the end of the data type, otherwise it will be a required value."

I am aware of that. I tried it once a while back and IIRC there was some kind of issue back than so I discarded the change. I may look into this again.

**Comment by taylortbb** [comment]
Setting user and password to an empty string worked, thanks!

I normally edit in UI mode, I only went to YAML mode as a result of clearing the text boxes not working (and I double checked there was no whitespace or anything left behind). However, now upon returning to UI mode, it does work. That makes me think editing in YAML mode has possibly left some state behind? When I clear the boxes in UI mode they outline in red, suggesting HA still believes they're invalid input, but now the save button works (previously I'd get an error about them being required).

If you don't want to make the fields optional I'd suggest changing the language in the README from "The credentials must be removed" to "The credentials must be set to an empty string ("" in YAML mode)".

**Comment by casperklein** [comment]
> If you don't want to make the fields optional

If there are no drawbacks, I'll make those fields optional.

I've applied the change in the dev repo: https://github.com/casperklein/homeassistant-addons-dev

You might give this a try. So far, it looks good and I couldn't find an issue. I think older HA versions, omit empty optional options in the config yaml file, which broke the script handling these options (expecting them to be present, at least with empty values)
Nowadays, empty optional options seem to be present in the config file.

**Pull request merged**
